### ISSUE TITLE
is_hiseqx_run should come from data in run folder

### ISSUE THREAD

**Issue by dkj** [wtsi-npg/npg_seq_pipeline#158]
i.e. it should come from the info available in the run folder like runParameters.xml and not come from the tracking system.

Should allow us to remove some of the npg xml in t/data

**Comment by dkj** [comment]
Alternatively:

1. Check for absence of ```Data/Intensities/L001/s_1_1101.clocs``` and ```Data/Intensities/L001/s_1_1101.locs```.
2. And/or for presence of ```Data/Intensities/s.locs```.

And replace method with ```is_ordered_flowcell```.

**Comment by mgcam** [comment]
Resoleved via https://github.com/wtsi-npg/npg_seq_pipeline/pull/281
