### ISSUE TITLE
rename boolean is_hiseqx_run 

### ISSUE THREAD

**Issue by srl147** [wtsi-npg/npg_seq_pipeline#163]
The name of the boolean is_hiseqx_run should be changed to reflect the fact it is also true for HiSeq 4000 runs. Currently this switch is used to skip the basecall_stats job (because the stats files don't exists), revcomp the second tag sequence and run bwa mem if sample is aligned with p4. is_ordered_flowcell may be a better name but we should ensure the resulting actions are only/always appropriate for ordered flowcells. In fact we may need two separate switches, the NextSeq doesn't generate stats files but it isn't an ordered flowcell.

**Comment by mgcam** [comment]
Resoleved via https://github.com/wtsi-npg/npg_seq_pipeline/pull/281
