### ISSUE TITLE
Specify limit groups when submitting certain jobs to wr

### ISSUE THREAD

**Issue by sb10** [wtsi-npg/npg_seq_pipeline#437]
wr v0.18 will have a new `--limit_grps` option to `wr add`.

For particular steps in the pipeline that might need to be limited (ask @srl147 for details) in the number of jobs that run simultaneously, the `wr add` call that results should include `--limit_grps stepname:n`, where 'stepname' could be the literal name of the step, or perhaps whatever currently forms the value of `-i`, and 'n' is the integer limit, eg. 1 to only run 1 job for that step at once.

For optimal performance, `--limit_grps` should _not_ be supplied if the step will not typically need to be limited. In special cases, `wr mod` can always be used to manually add a limit group after the job has been added. `wr limit` can be used to manually change limits afterwards as well.

**Comment by mgcam** [comment]
This has been implemented
