### ISSUE TITLE
no_auto , no_auto_analysis, no_auto_archive tags

### ISSUE THREAD

**Issue by mgcam** [wtsi-npg/npg_seq_pipeline#645]
to prevent runs going to analysis or archival

**Comment by mgcam** [comment]
See https://github.com/wtsi-npg/npg_tracking/pull/619 for listing of tags

**Comment by dkj** [comment]
We'll need to alter the archival and analysis daemons to skip over runs if such a tag is set for the run in npg_tracking.
Example of similar idea elsewhere https://github.com/wtsi-npg/npg_qc/blob/devel/bin/npg_mqc_skipper#L75
